---
- name: leapp_missing_efibootmgr | Install efibootmgr package - required on EFI systems
  block:
    - name: leapp_missing_efibootmgr | Install efibootmgr package
      ansible.builtin.dnf:
        name: efibootmgr
        state: present
      when: ansible_distribution == 'RedHat' and ansible_distribution_major_version|int == 8
    - name: leapp_missing_efibootmgr | Install efibootmgr package
      ansible.builtin.yum:
        name: efibootmgr
        state: present
      when: ansible_distribution == 'RedHat' and ansible_distribution_major_version|int == 7  

...
